### ISSUE TITLE
ActionBarCommon 可以加一个 titleTextStyle 属性吗，需要设置标题加粗

### ISSUE THREAD

**Issue by wangrui460** [goweii/ActionBarEx#10]
ActionBarCommon 可以加一个 titleTextStyle 属性吗，需要设置标题加粗

**Comment by goweii** [comment]
建议使用ActionBarSuper，这个支持的属性更多

**Comment by wangrui460** [comment]
从 ActionBarCommon 替换到 ActionBarSuper 废了老大劲了~
