### ISSUE TITLE
设置状态字体颜色后，ActionBarCommon会往下移

### ISSUE THREAD

**Issue by wenqian-cai-tuya** [goweii/ActionBarEx#12]
设置状态字体颜色后，ActionBarCommon会往下移
getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);
请问如果不调用此方法，如何修改状态栏颜色？

**Comment by goweii** [comment]
官方Android系统只能通过修改SYSTEM_UI_FLAG_LIGHT_STATUS_BAR参数控制状态栏图标颜色，只是部分国产系统在Android支持这个参数之前就引入了自己的控制方法，需要手动适配。

**Comment by wenqian-cai-tuya** [comment]
将 app:ab_autoImmersion="false" 设置为false的话，就可以了

**Comment by wenqian-cai-tuya** [comment]
当ab_autoImmersion 和ab_statusBarVisible都设置为true时，无法通过ab_statusBarMode改变状态栏颜色

**Comment by wenqian-cai-tuya** [comment]
Thanks for your message
