### ISSUE TITLE
你好，发现了一个奔溃的问题(界面由于内存不足被回收后重建过程的一个奔溃)

### ISSUE THREAD

**Issue by SwordSware** [goweii/ActionBarEx#14]
报错信息：Process: com.pasaruang.pinjaman.dana.tunai.uang.loan, PID: 32523
    java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class androidx.appcompat.widget.Toolbar$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/action_bar. Make sure other views do not use the same id.
![image](https://user-images.githubusercontent.com/12179448/83856592-5f831280-a74c-11ea-89d0-a6c26ac63bf2.png)
复现步骤：开发者模式中设置不保留活动以模拟内存不足被回收的状态->主页中的头部用的per.goweii.actionbarex.common.ActionBarCommon ，然后主页随便跳转一个页面，再点击返回到主页->主页重建->奔溃
关键点：action_bar.xml 中的android:id="@+id/action_bar"
原因：暂未查明

**Comment by goweii** [comment]
你改个id就好了，action_bar跟系统重复了

**Comment by SwordSware** [comment]
> 你改个id就好了，action_bar跟系统重复了

那就需要把你的代码下下来，作为module，再来修改了，我想着这样其他人也会碰到的

谢谢

**Comment by SwordSware** [comment]
> 你改个id就好了，action_bar跟系统重复了

是不是用新版的就可以了，我之前用的是3.2.2 ，我下载最新版代码中查找不到action_bar这样的id，应该是加了前缀

**Comment by goweii** [comment]
新版加前缀了，你升级下就好
