### ISSUE TITLE
SimpleActionBar在xml里配置ab_auto_immersion="false"无效

### ISSUE THREAD

**Issue by zaaach** [goweii/ActionBarEx#4]
设置为false，标题栏还是会多出来一块布局

**Comment by goweii** [comment]
已更新：implementation 'com.github.goweii:ActionBarEx:2.2.9'
布局中设置ab_status_bar_visible="false"可隐藏状态栏占位

**Comment by zaaach** [comment]
Thanks♪(･ω･)ﾉ
