### ISSUE TITLE
你说的这些用toolbar就能做啊

### ISSUE THREAD

**Issue by vejei** [goweii/ActionBarEx#5]
> 如果要自定义ActionBar的背景呢？要让背景显示一个图片呢？要让图片延伸到状态栏下面呢？要让背景实现半透明高斯模糊效果呢？要限定按钮图标的大小呢？要自定义中间标题的背景呢？要显示一个搜索框呢？要让搜索框带有清空和搜索图标呢？要自定义搜索框样式呢？要在网络请求时显示一个Loading效果呢？

现在官方文档里面是推荐使用`Toolbar`取代`ActionBar`的，`Toolbar`就可以实现你说的这些了啊

让背景显示图片
```
<androidx.appcompat.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="@android:color/white"  // 可以直接设置背景图
            app:contentInsetStart="0dp">

// 或者在这里用ImageView
        <ImageView
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:src="@mipmap/ic_launcher"
                android:scaleType="centerCrop"

        />

    </androidx.appcompat.widget.Toolbar>
```
`Toolbar`里面不仅可以放`ImageView`，还可以放`RelativeLayout`之类的布局，这些实现起来就更没问题了
> 要自定义中间标题的背景呢？要显示一个搜索框呢？要让搜索框带有清空和搜索图标呢？要自定义搜索框样式呢？

至于
> 要让背景实现半透明高斯模糊效果呢

这个就不应该是一个导航栏应该考滤的了吧，应该是`ImageView`的事了

还有
> 要在网络请求时显示一个Loading效果呢？

在布局里面加一个进度条就好了啊

**Comment by goweii** [comment]
嗯，Toolbar是可以实现的，但是大部分app都不会使用原生toolbar效果，这时基本都是要内嵌子布局的。这样就存在一个问题，50个页面就有50处重复的布局代码，当然也可以用include引入，但是就没法在xml预览效果了，标题图标这些都得在代码动态设置，代码量就加大了。还有就是关于沉浸式状态栏的适配和状态栏的暗亮色模式，toolbar是不提供这个功能的。我这里只是把这些重复操作抽取出来方便定制和使用，尽可能通过最少的代码实现相同的效果。

**Comment by vejei** [comment]
所以不是像你说的官方部件不能做，而是可能会重复

而
> 还有就是关于沉浸式状态栏的适配和状态栏的暗亮色模式，toolbar是不提供这个功能的

这个你都说是状态栏了，那就不关导航栏什么事了吧，而且状态栏颜色也是可以调的

**Comment by goweii** [comment]
第一点，没说官方的不能实现呀！

> 先说说官方的。官方的在不同系统上的风格并不统一，自定义项太少，不能满足开发需求，所以才涌现了这么多的开源项目。

后面那些举例不是在比较其他第三方框架吗？

> 网上开源的。网上的已有的，我发现的，用过的大部分都是直接封装一个固定样式的布局，或控制控件的显示隐藏，或动态添加需要的控件。但也仅限于自定义左右图标的和中间标题的个数和样式。如果要自定义ActionBar的背景呢？要让背景显示一个图片呢？要让图片延伸到状态栏下面呢？要让背景实现半透明高斯模糊效果呢？要限定按钮图标的大小呢？要自定义中间标题的背景呢？要显示一个搜索框呢？要让搜索框带有清空和搜索图标呢？要自定义搜索框样式呢？要在网络请求时显示一个Loading效果呢？等等这些需求都是无法满足的。而且我相信这样的需求不在少数。

而且不是也加粗说明了下：

> 也可能有可以实现的框架，只是我还没发现。


第二点，我觉得导航栏的自定义一般都是伴随状态栏适配的，所以集成进去了，这只是一个封装划分的问题吧！
