### ISSUE TITLE
loading_bar.xml有问题

### ISSUE THREAD

**Issue by yanyusanqian** [goweii/ActionBarEx#7]
导入框架的时候都没问题，都导入成功了，但是在运行的时候，一直提示我找不到me.zhanghai.android.materialprogressbar.MaterialProgressBar，不知道是缺了什么？然后我不得已删了这个前景层...就出现了ActionBar和状态栏重叠的情况，头疼，希望能早点解决

**Comment by goweii** [comment]
你是导入的demo运行吗？那个loading是一个第三方，框架里是没有的只在demo中引用了。和状态栏重叠应该是设置了不显示状态栏占位。

**Comment by yanyusanqian** [comment]
哦我知道了，我直接用的demo里面的一部分代码，我以为demo里面用的所有的都是框架里的，刚刚删掉了这一段，然后把状态栏改回来了，解决了，谢谢。：）
